[colors]
rx = [0, 255, 70]
tx = [0, 150, 0]
total = [50, 255, 50]
border_active = [0, 255, 0]
border_inactive = [0, 50, 0]
border_focus = [200, 255, 200]
highlight_fg = [0, 0, 0]
highlight_bg = [0, 255, 0]
app_name = [0, 255, 0]
country = [0, 200, 0]
payload = [150, 255, 150]
dim = [0, 100, 0]
